### ISSUE TITLE
Slides not working in Chrome stable and Canary

### ISSUE THREAD

**Issue by shadeed** [LeaVerou/html-secrets#1]
Hello Lea,

Thanks so much for sharing the slides. There is a tiny issue and not sure if it's intended or not, in Chrome stable/Canary (1440 * 736) the content overlaps like the screenshot:

![lea-html-secrets](https://cloud.githubusercontent.com/assets/8038659/17285804/d66505c0-57cd-11e6-9982-36228f3fe6cc.jpg)

When adding `height: 100vh` to  all sections with `.slide` class, it works good for me.

Looking forward to your thoughts.

Thanks again,

**Comment by LeaVerou** [comment]
OMG, this is broken in so many ways I've lost count. Which version/OS?

**Comment by shadeed** [comment]
@LeaVerou I'm using OSX El Capitan and below are the versions for both Canary and Stable versions:
Chrome Canary: 54.0.2813.0 (64-bit)
Chrome Stable: 51.0.2704.106 (64-bit)

**Comment by harikt** [comment]
I too tried it, but it specifically mentions the resolution which was not mine.

**Comment by LeaVerou** [comment]
I just tried it in Browserstack and the only issue I could see was that I forgot to @font-face some fonts. Are there any resources not loading? Can you check?

**Comment by shadeed** [comment]
Yes there are some resources that doesn't get loaded:

<img width="1106" alt="screen shot 2016-08-01 at 11 29 09 pm" src="https://cloud.githubusercontent.com/assets/8038659/17307678/0a649e82-583f-11e6-9f84-a4950b73b334.png">

**Comment by LeaVerou** [comment]
Oh, you're viewing from localhost. That explains it! You need to clone a bunch of my other repos (csss, prefixfree, incrementable, multirange) in directories adjacent to it to make it work locally. If you'd rather avoid the hassle, view it online?

**Comment by harikt** [comment]
@LeaVerou thank you. Probably I missed the link to online. May be it was when you just opensourced it. Looks nice.

**Comment by shadeed** [comment]
@LeaVerou Oh, sorry for the confusion! Works fine for me and Thanks a lot of the useful slides. :)
